# 项目相关配置
flyhigh:
  # 名称
  name: flyhigh
  # 版本
  version: 3.7.0
  # 版权年份
  copyrightYear: 2021
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/flyhigh/uploadPath，Linux配置 /home/flyhigh/uploadPath）
  profile:  /data/flyhigh-projects/workorder/file
  # 文件路径-Windows配置
  winProfile: D:/flyhigh-projects/workorder/file
  # 文件路径-Linux配置
  linuxProfile: ${flyhigh.profile}
  # 获取ip地址开关
  addressEnabled: true
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: char


# 日志配置
#logging:
#  level:
#    com.flyhigh: info
#    org.springframework: warn
logging:
  level:
    com.flyhigh: DEBUG
    org.springframework: warn
# 数据源配置
spring:
  # redis 配置
  redis:
    # 地址
    host: 118.25.46.110
    # 端口，默认为6379
    port: 26379
    # 数据库索引
    database: 4
    # 密码
    password: bimu@2023_#redis.$
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://118.25.46.110:23306/workorder?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: workorder_account
        password: Flyhigh_workorder_account$2024
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: flyhigh
        login-password: flyhigh@123456
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  #rabbitmq配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /

web:
  returnUrl: ''

app:
  # 新增安全-登录接口
  safetyLoginUrl: http://36.139.119.121:82/admin-api/login
  # 微信模板消息账单地址
  wxTemplateBillUrl: http://assets.newcity.szbimu.cn/wx/wx_auth.html?r=


# 个推
gt:
  appId: rDIvwdzzAB6gBHYeXKPwj1
  appKey: K9XG2qKmDI94NNWg9KhQX5
  masterSecret: nNoswoXsm899nOc9IFRfI
  androidPackage: plus.H5DFB6309


# 公众号配置
wx:
  mp:
    app-id: temp # 公众号的APPID
    secret: temp # 公众号的appsecret
    token: temp # 接口配置里的Token
    aes-key: temp # 接口配置的EncodingAESKey
    state: temp # 获取code所需要的state
    config-storage:
      type: redistemplate

  # 微信支付配置
  pay:
    app-id: app-id
    mch-id: mch-id
    mch-key: mch-key
    subAppId:
    subMchId:
    key-path: key-path

  # 微信模板ID
  mp-template-id:
    # 审核结果通知
    authProcess: temp
    # 租金缴费
    rentPay: temp
    # 账单支付
    billPay: temp
    # 出账通知
    billNotice: temp
    # 退租待确认通知
    leaseNotice: temp
    # 房租催缴通知
    LeaseCallNotice: temp

  # 微信消息
  message:
    open: false # true 发送微信消息通知 false 关闭微信消息通知
